import {
  DeleteObjectsCommand,
  GetObjectCommand,
  HeadObjectCommand,
  ListObjectsV2Command,
  NotFound,
  PutObjectCommand,
  S3Client,
} from '@aws-sdk/client-s3';
import { getSignedUrl } from '@aws-sdk/s3-request-presigner';
import { HttpStatus, Injectable, OnModuleDestroy } from '@nestjs/common';
import { ConfigService } from '@nestjs/config';
import type { Env } from '../config/env';
import { AppException } from '../errors/app.exception';
import { ErrorCode } from '../errors/error-codes';
import { presignGetUrl } from './sigv4';

interface StorageConfig {
  endpoint: string;
  bucket: string;
  accessKeyId: string;
  secretAccessKey: string;
}

const REGION = 'auto';
const HOUR_MS = 60 * 60 * 1000;
/** Upload URLs are short-lived (photo-pipeline skill). */
export const UPLOAD_URL_TTL_SECONDS = 10 * 60;

/**
 * The private photo bucket (Cloudflare R2, MinIO locally). Nothing here is
 * public: clients get pre-signed URLs. Keys are always generated by us.
 */
@Injectable()
export class StorageService implements OnModuleDestroy {
  private readonly config: StorageConfig | null;
  private readonly client: S3Client | null;

  constructor(config: ConfigService<Env, true>) {
    const bucket = config.get('R2_BUCKET', { infer: true });
    const accessKeyId = config.get('R2_ACCESS_KEY_ID', { infer: true });
    const secretAccessKey = config.get('R2_SECRET_ACCESS_KEY', { infer: true });
    const endpoint =
      config.get('R2_ENDPOINT', { infer: true }) ??
      `https://${config.get('R2_ACCOUNT_ID', { infer: true })}.r2.cloudflarestorage.com`;
    if (!bucket || !accessKeyId || !secretAccessKey) {
      this.config = null;
      this.client = null;
      return;
    }
    this.config = { endpoint, bucket, accessKeyId, secretAccessKey };
    this.client = new S3Client({
      region: REGION,
      endpoint,
      // R2 and MinIO both accept path-style URLs; no bucket DNS needed.
      forcePathStyle: true,
      // The SDK's default checksums would sign a CRC32 of an empty body into
      // pre-signed PUT URLs, which R2 and MinIO then reject.
      requestChecksumCalculation: 'WHEN_REQUIRED',
      responseChecksumValidation: 'WHEN_REQUIRED',
      credentials: { accessKeyId, secretAccessKey },
    });
  }

  get enabled(): boolean {
    return this.config !== null;
  }

  /** 503 when storage isn't configured (like Apple sign-in without its keys). */
  assertEnabled(): void {
    if (!this.enabled) {
      throw new AppException(
        ErrorCode.SERVICE_UNAVAILABLE,
        HttpStatus.SERVICE_UNAVAILABLE,
        {
          service: 'storage',
        },
      );
    }
  }

  /** PUT URL bound to the content type and length the client declared. */
  presignPut(
    key: string,
    contentType: string,
    contentLength: number,
  ): Promise<string> {
    const { client, config } = this.require();
    return getSignedUrl(
      client,
      new PutObjectCommand({
        Bucket: config.bucket,
        Key: key,
        ContentType: contentType,
        ContentLength: contentLength,
      }),
      {
        expiresIn: UPLOAD_URL_TTL_SECONDS,
        signableHeaders: new Set(['content-type', 'content-length']),
      },
    );
  }

  /**
   * GET URL valid for at least an hour. Signed at the start of the current
   * hour, so the URL stays the same for an hour and clients can cache images.
   */
  signedGetUrl(key: string, now = new Date()): string | null {
    if (!this.config) return null;
    return presignGetUrl({
      endpoint: this.config.endpoint,
      region: REGION,
      bucket: this.config.bucket,
      key,
      accessKeyId: this.config.accessKeyId,
      secretAccessKey: this.config.secretAccessKey,
      signingDate: new Date(Math.floor(now.getTime() / HOUR_MS) * HOUR_MS),
      expiresInSeconds: 2 * 60 * 60,
    });
  }

  /** Size and type of an object, or null when it doesn't exist. */
  async head(
    key: string,
  ): Promise<{ bytes: number; contentType?: string } | null> {
    const { client, config } = this.require();
    try {
      const result = await client.send(
        new HeadObjectCommand({ Bucket: config.bucket, Key: key }),
      );
      return {
        bytes: result.ContentLength ?? 0,
        contentType: result.ContentType,
      };
    } catch (error) {
      if (
        error instanceof NotFound ||
        (error as { name?: string }).name === 'NotFound'
      ) {
        return null;
      }
      throw error;
    }
  }

  async get(key: string): Promise<Buffer> {
    const { client, config } = this.require();
    const result = await client.send(
      new GetObjectCommand({ Bucket: config.bucket, Key: key }),
    );
    if (!result.Body) throw new Error('empty object body');
    return Buffer.from(await result.Body.transformToByteArray());
  }

  async put(key: string, body: Buffer, contentType: string): Promise<void> {
    const { client, config } = this.require();
    await client.send(
      new PutObjectCommand({
        Bucket: config.bucket,
        Key: key,
        Body: body,
        ContentType: contentType,
      }),
    );
  }

  /** Deletes every object under the prefix. Idempotent. */
  async deletePrefix(prefix: string): Promise<number> {
    const { client, config } = this.require();
    let deleted = 0;
    let token: string | undefined;
    do {
      const page = await client.send(
        new ListObjectsV2Command({
          Bucket: config.bucket,
          Prefix: prefix,
          ContinuationToken: token,
        }),
      );
      const keys = (page.Contents ?? []).flatMap((object) =>
        object.Key ? [{ Key: object.Key }] : [],
      );
      if (keys.length) {
        await client.send(
          new DeleteObjectsCommand({
            Bucket: config.bucket,
            Delete: { Objects: keys, Quiet: true },
          }),
        );
        deleted += keys.length;
      }
      token = page.IsTruncated ? page.NextContinuationToken : undefined;
    } while (token);
    return deleted;
  }

  onModuleDestroy(): void {
    this.client?.destroy();
  }

  private require(): { client: S3Client; config: StorageConfig } {
    this.assertEnabled();
    return { client: this.client!, config: this.config! };
  }
}
